Repository IN-SOPT-Joint-Seminar-OLIVEYOUNG/OLIVEYOUNG-AOS, pull requests merged in 2022-11, with the labels that each got.

#6 [feat] 디테일 뷰 틀 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/oliveyoung/presentation/DetailActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/HomeFragment.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/LikeFragment.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/MainActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/MenuFragment.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/MyFragment.kt
  app/src/main/java/com/sopt/oliveyoung/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/img_skincare.png
  app/src/main/res/drawable-xhdpi/img_skincare.png
  app/src/main/res/drawable-xxhdpi/img_skincare.png
  app/src/main/res/drawable-xxxhdpi/img_skincare.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_detail.xml
  app/src/main/res/drawable/ic_hamburger_menu.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_selected_home.xml
  app/src/main/res/drawable/ic_selected_like.xml
  app/src/main/res/drawable/ic_selected_my.xml
  app/src/main/res/drawable/ic_unselected_home.xml
  app/src/main/res/drawable/ic_unselected_like.xml
  app/src/main/res/drawable/ic_unselected_my.xml
  app/src/main/res/drawable/img_skincare.png
  app/src/main/res/drawable/selector_menu_icon_home.xml
  app/src/main/res/drawable/selector_menu_icon_like.xml
  app/src/main/res/drawable/selector_menu_icon_my.xml
  app/src/main/res/drawable/shape_border_top_radius_10.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 😘 영진 😘, 👀 디테일 뷰 👀, 🔥 In Progress 🔥

#7 [feat] #3 검색 결과 뷰 전체 틀 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/oliveyoung/domain/CosmeticBrandInfo.kt
  app/src/main/java/com/sopt/oliveyoung/domain/CosmeticProductInfo.kt
  app/src/main/java/com/sopt/oliveyoung/domain/PopularSearchInfo.kt
  app/src/main/java/com/sopt/oliveyoung/domain/RecentProductInfo.kt
  app/src/main/java/com/sopt/oliveyoung/domain/RecentSearchInfo.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/CosmeticBrandAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/CosmeticProductAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/PopularSearchAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/RecentProductAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/RecentSearchAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/SearchActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/SearchResultActivity.kt
  app/src/main/java/com/sopt/oliveyoung/util/BindingAdapters.kt
  app/src/main/res/drawable-hdpi/bg_popular_search.xml
  app/src/main/res/drawable-hdpi/bg_recent_search.xml
  app/src/main/res/drawable-hdpi/bg_searchbar.xml
  app/src/main/res/drawable/ic_checkbox.xml
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/shape_border_radius_10.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_search_error.xml
  app/src/main/res/layout/activity_search_result.xml
  app/src/main/res/layout/item_cosmetic_brand.xml
  app/src/main/res/layout/item_cosmetic_product.xml
  app/src/main/res/layout/item_popular_search.xml
  app/src/main/res/layout/item_recent_product.xml
  app/src/main/res/layout/item_recent_search.xml
Labels: 😘 지은 😘, 🔎 검색 뷰 🔎, 🔥 In Progress 🔥

#9 [feat] 디테일 뷰 세부 레이아웃 구현
  app/src/main/java/com/sopt/oliveyoung/presentation/DetailActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/custom/HashtagView.kt
  app/src/main/res/drawable/ic_dropdown_down.xml
  app/src/main/res/drawable/ic_dropdown_up.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_search_small.xml
  app/src/main/res/drawable/ic_selected_like.xml
  app/src/main/res/drawable/ic_star1.xml
  app/src/main/res/drawable/ic_star5.xml
  app/src/main/res/drawable/selector_dropdown_button.xml
  app/src/main/res/drawable/shape_border_radius_15.xml
  app/src/main/res/font/inter_r.ttf
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_cosmetic_product.xml
  app/src/main/res/layout/item_product_type.xml
  app/src/main/res/layout/layout_detail_deliverey_section.xml
  app/src/main/res/values/strings.xml
Labels: 😘 영진 😘, 👀 디테일 뷰 👀, ✨ Done ✨

#11 [init] 서버 통신 기초 세팅
  app/build.gradle
  app/src/main/java/com/sopt/oliveyoung/data/ApiFactory.kt
  app/src/main/java/com/sopt/oliveyoung/data/OliveYoungService.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseBase.kt
  app/src/main/java/com/sopt/oliveyoung/util/extensions/CallExt.kt
Labels: 😘 영진 😘, 🚀 서버 통신 🚀, ✨ Done ✨

#15 [feat] 상세 정보 뷰 관련 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/oliveyoung/application/OliveYoungApplication.kt
  app/src/main/java/com/sopt/oliveyoung/data/OliveYoungService.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseProductDetailDto.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseProductLikeStateDto.kt
  app/src/main/java/com/sopt/oliveyoung/domain/CosmeticProductInfo.kt
  app/src/main/java/com/sopt/oliveyoung/domain/entity/CosmeticProductDetail.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/DetailActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/detail/ProductDetailViewModel.kt
  app/src/main/java/com/sopt/oliveyoung/util/BindingAdapters.kt
  app/src/main/java/com/sopt/oliveyoung/util/OliveYoungDebugTree.kt
  app/src/main/res/drawable/img_product_detail_sample.jpeg
  app/src/main/res/drawable/selector_dropdown_button.xml
  app/src/main/res/drawable/selector_menu_icon_like.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_cosmetic_product.xml
  app/src/main/res/layout/layout_detail_deliverey_section.xml
Labels: 😘 영진 😘, 🚀 서버 통신 🚀, ✨ Done ✨

#17 [feat] #12 검색 서버통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/oliveyoung/data/ApiFactory.kt
  app/src/main/java/com/sopt/oliveyoung/data/OliveYoungService.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseSearchDto.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseSearchResultDto.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/CosmeticBrandAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/CosmeticProductAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/SearchActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/SearchResultActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/SearchViewModel.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/search/PopularSearchAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/search/RecentSearchAdapter.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/search/SearchResultActivity.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_search_result.xml
  app/src/main/res/layout/item_cosmetic_brand.xml
Labels: 😘 지은 😘, 🚀 서버 통신 🚀, ✨ Done ✨

#18 [feat] #16 홈 화면 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/oliveyoung/data/OliveYoungService.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseRecommendProductDto.kt
  app/src/main/java/com/sopt/oliveyoung/data/dto/response/ResponseSearchDto.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/HomeFragment.kt
  app/src/main/java/com/sopt/oliveyoung/presentation/HomeViewModel.kt
Labels: 😘 민영 😘, 🚀 서버 통신 🚀, ✨ Done ✨
